---
format:
  html:
    toc: true
    toc-location: right
    toc-depth: 4
---

## Academic positions

[<font size='3' color='grey'>2022--</font>]{.column-sidebar}
[Postdoctoral research scientist <br> **Institute for Phonetics and Speech Processing, Ludwig Maximilian University, Munich**]{.column-body}

[<font size='3' color='grey'>2021--2022</font>]{.column-sidebar}
[Two fixed-term part-time positions as lecturer <br> **Amsterdam Center for Language and Communication, University of Amsterdam**]{.column-body}

[<font size='3' color='grey'>2018--2022</font>]{.column-sidebar}
[PhD fellow <br> **Leiden University Centre for Linguistics**]{.column-body}

[<font size='3' color='grey'>2013--2017</font>]{.column-sidebar}
[Various teaching and research assistant positions <br> **School of Culture and Society, Aarhus University**]{.column-body}

## Education

[<font size='3' color='grey'>2023</font>]{.column-sidebar}
[**PhD** in Linguistics <br> **Leiden University**]{.column-body}

[<font size='3' color='grey'>2018</font>]{.column-sidebar}
[**MA** in Linguistics <br> **Aarhus University**]{.column-body}

[<font size='3' color='grey'>2016</font>]{.column-sidebar}
[**BA** in Linguistics and China Studies <br> **Aarhus University**]{.column-body}

## Internationalization

[<font size='3' color='grey'>2020</font>]{.column-sidebar}
[**The Arctic University of Norway -- Tromsø** <br>
Center for Advanced Studies in Linguistics <br>
3 month research visit]{.column-body}

[<font size='3' color='grey'>2018</font>]{.column-sidebar}
[**Aarhus University** <br>
Peter Skautrup Centre for Jutlandic Dialect Research <br>
2 month research visit]{.column-body}

[<font size='3' color='grey'>2017--2018</font>]{.column-sidebar}
[**KU Leuven** <br>
ResMA Advanced Studies in Linguistics <br>
Full semester exchange]{.column-body}

[<font size='3' color='grey'>2016</font>]{.column-sidebar}
[**Peking University** <br>
European--Chinese Language and Culture Programme <br>
Full semester exchange]{.column-body}

## Grants and awards

[<font size='3' color='grey'>2020</font>]{.column-sidebar}
[William Demant Fonden travel grant, €800 (annulled due to COVID-19 outbreak) <br>
Leids Universiteits Fonds travel grant, €1.600]{.column-body}

[<font size='3' color='grey'>2017</font>]{.column-sidebar}
[Aarhus University Arts travel grant, €550]{.column-body}

[<font size='3' color='grey'>2015</font>]{.column-sidebar}
[Aarhus University Arts travel grant, €800 <br>
Aarhus University Linguistics Department travel grant, €200]{.column-body}

## Conference and workshop organization

[<font size='3' color='grey'>2021</font>]{.column-sidebar}
[*Conference of the Student Organization of Linguistics in Europe* 29 <br>
Digital meeting hosted at Leiden University, 26--28 January]{.column-body}

[<font size='3' color='grey'>2018</font>]{.column-sidebar}
[*Nordic Interdisciplinary Conference on Discourse and Interaction* 5 <br>
Aarhus University, 21--23 November]{.column-body}

[<font size='3' color='grey'>2015</font>]{.column-sidebar}
[*Bias in Auditory Perception* <br>
Aarhus University, 18--20 September]{.column-body}

## Reviewing

#### Journal articles

*Computational Intelligence and Neuroscience* (2022) <br>
*Glossa* (2021) <br>
*Nydanske Sprogstudier* (2023)

#### Proceedings articles

*International Congress of Phonetic Sciences* (2023) <br>
*Møderne om udforskningen af det danske sprog* (2019, 2021)

#### Conference abstracts

*Laboratory Phonology* (2022) <br>
*Phonology in the Nordic Countries* (2021)

## Other service

#### Professional service and outreach

[<font size='3' color='grey'>2021--2023</font>]{.column-sidebar}
[Board member of *[Student Organization of Linguistics in Europe](https://www.universiteitleiden.nl/en/events/series/sole){target="_blank"}*]{.column-body}

[<font size='3' color='grey'>2017--2018</font>]{.column-sidebar}
[High school presentations with the *Danish Talk-in-Interaction* (DanTIN) group]{.column-body}

[<font size='3' color='grey'>2014--2015</font>]{.column-sidebar}
[Research assistant for the *Cognitive Creolistics* project at Aarhus University]{.column-body}

[<font size='3' color='grey'>2014</font>]{.column-sidebar}
[Establishing and editing working papers journal *[Skrifter om Samtalegrammatik](https://samtalegrammatik.dk/tidsskrift){target="_blank"}*]{.column-body}

[<font size='3' color='grey'>2013--2018</font>]{.column-sidebar}
[Establishing and editing [samtalegrammatik.dk](https://samtalegrammatik.dk){target="_blank"}]{.column-body}

#### University service

[<font size='3' color='grey'>2017</font>]{.column-sidebar}
[Student member of grade appeal board]{.column-body}

[<font size='3' color='grey'>2015--2018</font>]{.column-sidebar}
[Exercises with new students during intro week in BA Linguistics, Aarhus University]{.column-body}

[<font size='3' color='grey'>2014</font>]{.column-sidebar}
[Mentor for new undergraduate students in BA Linguistics, Aarhus University]{.column-body}

[<font size='3' color='grey'>2013</font>]{.column-sidebar}
[Organizing and hosting intro week for new undergraduate students in BA Linguistics, Aarhus University]{.column-body}

## Professional memberships

[<font size='3' color='grey'>2023--</font>]{.column-sidebar}
[[International Phonetic Association](https://www.internationalphoneticassociation.org/){target="_blank"}]{.column-body}

[<font size='3' color='grey'>2021--</font>]{.column-sidebar}
[[Association for Laboratory Phonology](https://labphon.org/){target="_blank"}]{.column-body}

## Affiliated research networks

[<font size='3' color='grey'>2022--</font>]{.column-sidebar}
[[Empirical Foundations of Phonology (EmpiPhon)](https://aclc.uva.nl/content/research-groups/empiphon/empiphon.html){target="_blank"}]{.column-body}

[<font size='3' color='grey'>2020--2022</font>]{.column-sidebar}
[Open Science Community, Leiden]{.column-body}

[<font size='3' color='grey'>2020--2021</font>]{.column-sidebar}
[Tromsø/Verona phonology circle]{.column-body}

[<font size='3' color='grey'>2017--</font>]{.column-sidebar}
[[Sounds of Language and Speech](https://soundsoflanguageandspeech.wordpress.com/){target="_blank"} (Aarhus University)]{.column-body}

[<font size='3' color='grey'>2015</font>]{.column-sidebar}
[Danish-accented Chinese (Aarhus University)]{.column-body}

[<font size='3' color='grey'>2013--2018</font>]{.column-sidebar}
[Danish Talk-in-Interaction (DanTiN)]{.column-body}

## Languages

**Danish**: Native

**English**: Full professional proficiency

**Dutch**: Passive proficiency very high, active proficiency good <br>
Coursework to B1 level in 2018--2019

**German**: Passive proficiency very high, active proficiency decent <br>
3 years of elementary school courses in 2005--2008

**Standard Chinese**: Decent reading, basic passive and communicative proficiency <br>
Coursework to B2 level in 2014--2016

**Norwegian**: Fluent reading and very high passive proficiency

**Swedish**: Near-fluent reading and decent passive proficiency

**Icelandic**: Basic reading skills <br>
Followed intense summer school (2015)

**French**: Basic reading skills

**Castilian Spanish**: Very low proficiency <br>
3 years of high school courses (2008--2011)

**Arabic**: Some passive knowledge but no proficiency <br>
Followed evening school course (2014)

## Coding and technical skills

`R`: High proficiency <br>
Data processing, plotting, acoustic analysis, typesetting (with RMarkdown and Quarto), package preparation and maintenance, and statistical analysis (see below)

`Praat`: High proficiency <br>
Acoustic analysis, scripting

`LaTeX`: Decent proficiency <br>
Typesetting, figures, plotting

`Git`: Decent proficiency <br>
Version control, collaborative projects

`VBA`: Basic proficiency <br>
Data preprocessing

`bash`: Basic proficiency <br>
Various types of task automatization

`HTML`: Basic proficiency

`Python`: Basic proficiency

## Statistical expertise

Linear and logistic (mixed) models <br>
Generalized additive (mixed) models <br>
Functional (mixed) models <br>
Growth curve analysis <br>
(Functional) principal component analysis <br>
Multiple correspondence analysis

## Teaching

### Full term courses

#### Ludwig Maximilian University, Munich

[<font size='3' color='grey'>2023</font>]{.column-sidebar}
[*Phonetics and statistics* <br>
BA3 Phonetics and Speech Processing <br>
Taught seminars, graded weekly exercises <br>
Course coordinator: James Kirby]{.column-body}

#### University of Amsterdam

[<font size='3' color='grey'>2022</font>]{.column-sidebar}
[*Introduction to linguistics* <br>
BA1 Linguistics <br>
Taught seminars (two groups), graded final presentations <br>
Course coordinator: Enoch O. Aboh]{.column-body}

[<font size='3' color='grey'>2021</font>]{.column-sidebar}
[*Phonetics* <br>
BA1 Linguistics <br>
Taught seminars (two groups) in a hybrid format, graded weekly exercises <br>
Course coordinator: Marijn van 't Veer <br>
*Nominated for the Faculty of Humanities Education Award 2022*]{.column-body}

[<font size='3' color='grey'>2021</font>]{.column-sidebar}
[*Phonology* <br>
BA2 Linguistics <br>
Taught seminars in a hybrid format, graded exercises and final presentations <br>
Course coordinator: Silke Hamann <br>
*Nominated for the Faculty of Humanities Education Award 2022*]{.column-body}

#### Leiden University

[<font size='3' color='grey'>2022</font>]{.column-sidebar}
[*Words, sentences, and sounds in interaction* <br>
BA3 English Language & Culture <br>
Co-taught and co-coordinated with Janet Grijzenhout]{.column-body}

[<font size='3' color='grey'>2022</font>]{.column-sidebar}
[*Analyzing English words and sounds* <br>
BA1 English Language & Culture <br>
Taught seminars (two groups) and gave one lecture <br>
Course coordinators: Bert Botma and Marion Elenbaas]{.column-body}

[<font size='3' color='grey'>2019--2021</font>]{.column-sidebar}
[*The phonetics of English* <br>
BA1 English Language & Culture <br>
2019: Taught seminars <br>
2020: Taught seminars (three groups in person, one group online) and gave one online lecture <br>
2021: Taught seminars in the first block <br>
Course coordinator: Bert Botma]{.column-body}

#### Aarhus University

[<font size='3' color='grey'>2016</font>]{.column-sidebar}
[*Understanding linguistics* <br>
BA1 Linguistics <br>
Taught seminars (two groups) <br>
Course coordinator: William McGregor]{.column-body}

[<font size='3' color='grey'>2014</font>]{.column-sidebar}
[*Structure, meaning, and use* <br>
BA2 Linguistics <br>
Teaching assistant, gave feedback on assignments <br>
Course coordinator: Jan Rijkhoff]{.column-body}

[<font size='3' color='grey'>2014</font>]{.column-sidebar}
[*Danish and the languages of the World* <br>
BA1 Linguistics <br>
Teaching assistant, gave feedback on assignments <br>
Course coordinator: Line Krogager Andersen]{.column-body}

[<font size='3' color='grey'>2013</font>]{.column-sidebar}
[*Phonetics and phonology* <br>
BA1 Linguistics <br>
Taught seminars (three groups), graded assignments <br>
Course coordinator: Marjoleine Sloos]{.column-body}

### Workshops

[<font size='3' color='grey'>2017</font>]{.column-sidebar}
[*Acoustics and Praat* <br>
3-hour workshop <br>
Department of Linguistics, Aarhus University]{.column-body}

### Guest lectures

[<font size='3' color='grey'>2021--2022</font>]{.column-sidebar}
[*Advanced phonology 2* <br>
MA Linguistics, Leiden University <br>
Course coordinator: Bert Botma]{.column-body}

[<font size='3' color='grey'>2020--2022</font>]{.column-sidebar}
[*Data management* <br>
Centre for Linguistics graduate school, Leiden University <br>
Course coordinators: Fieke Schoots and Kristina Hettne]{.column-body}

### Evaluation

[<font size='3' color='grey'>2021</font>]{.column-sidebar}
[Two BA theses in BA English Language & Culture, Leiden University]{.column-body}